import type { MerchItem, Product, RewardsCampaign, Settings } from '../types';

export const defaultSettings: Settings = {
  businessName: 'Candy Crackzzz',
  businessPhone: '',
  businessEmail: '',
  businessAddress: '',
  orderDestinationEmail: '',
  orderNotificationPhone: '',
  contactDestinationEmail: '',
  serviceArea: 'Spring Hill, FL and surrounding areas',
  aboutText: 'Candy Crackzzz is your ultimate destination for candy-coated fruit and custom treats.',
  socialLinks: { instagram: '', facebook: '', tiktok: '' },
  enableOrdering: true,
  enableCustomOrders: true,
  enableSeasonalSection: true,
  enableGallery: true,
  enableFeaturedSection: true,
  enableMerch: true,
  enableDonutzzz: false,
  showDonutzzzOnHome: false,
  showDonutzzzInMenu: false,
  enableDirtySodazzz: false,
  showDirtySodazzzOnHome: false,
  showDirtySodazzzInMenu: false,
  enablePickup: true,
  enableDelivery: true,
  directionsEnabled: true,
  deliveryDirectionsButtonEnabled: true,
  deliveryDirectionsNote: 'Tap for directions after your delivery address is confirmed.',
  deliveryFeeEnabled: false,
  deliveryFeeAmount: 10,
  minimumOrder: 20,
  showPricesPublicly: true,
  showSoldOutItems: true,
  allowRequestWithoutPrice: true,
  enableRewards: true,
  rewardsPointsPerDollar: 1,
  rewardsAwardOnCompletedOrder: true,
  rewardsAllowPromoStacking: false,
  rewardsTier1Points: 50,
  rewardsTier1Discount: 5,
  rewardsTier2Points: 100,
  rewardsTier2Discount: 12,
  rewardsTier3Points: 200,
  rewardsTier3Discount: 25,
  rewardsDoublePointsEnabled: false,
  rewardsFirstOrderBonusEnabled: false,
  rewardsFirstOrderBonusPoints: 10,
  rewardsBirthdayBonusEnabled: false,
  rewardsBirthdayBonusPoints: 15,
  rewardsSpendThresholdEnabled: false,
  rewardsSpendThresholdAmount: 50,
  rewardsSpendThresholdBonusPoints: 10,
  enableReferrals: true,
  referralReferrerBonusPoints: 15,
  referralReferredCustomerBonusPoints: 10,
  referralBonusOnFirstCompletedOrder: true,
  referralProgramDescription: 'Use a friend referral code at checkout so both of you can earn bonus points after the order is completed.',
  enablePromoTexts: false,
  promoTextsDescription: 'Customers who opt in can receive upcoming promotion texts later.',
  enablePayments: false,
  enableSquare: false,
  squarePaymentLink: '',
  squareInstructions: '',
  enableStripe: false,
  stripePaymentLink: '',
  stripeInstructions: '',
  enablePayPal: false,
  paypalContact: '',
  paypalInstructions: '',
  enableCashApp: false,
  cashAppTag: '',
  cashAppInstructions: '',
  enableVenmo: false,
  venmoUsername: '',
  venmoInstructions: '',
  enableZelle: false,
  zelleContact: '',
  zelleInstructions: '',
  enableQRCode: false,
  qrCodeImageBase64: '',
  qrCodeInstructions: '',
  enableManualInvoice: false,
  manualInvoiceInstructions: 'We will send you an invoice after confirming your order.',
  enableCashAtPickup: false,
  cashAtPickupInstructions: 'Pay cash when you pick up your order.',
  allowDepositOnly: false,
  allowFullPayment: true,
  allowCashAtPickup: false,
  allowManualInvoice: false,
  paymentInstructions: '',
  logoBase64: '',
  showLogo: true,
  helperEnabled: true,
  helperShowFloating: true,
  helperShowOnHome: true,
  helperShowOnMenu: true,
  helperShowOnMerch: true,
  helperShowOnCart: true,
  helperAllowMerchSuggestions: true,
  helperAllowRewardsSuggestions: true,
  helperAllowReferralSuggestions: true,
  helperAllowCustomOrderIdeas: true,
  helperGreeting: 'Need help picking something sweet? Tell me what flavors you like.',
  helperMaxRecommendations: 3,
  helperAllergyDisclaimer: 'Please confirm ingredients and allergy concerns before ordering.',
  helperFallbackMessage: 'I can help with Candy CrackZZZ flavors, fruit, candy-dipped treats, merch, rewards, pickup, delivery, or custom order ideas.',
  notificationSoundsEnabled: false,
  notificationSoundVolume: 0.7,
  orderSoundEnabled: true,
  messageSoundEnabled: true,
  generalSoundEnabled: true,
  notificationPollingEnabled: true,
  notificationPollingSeconds: 12,
  notificationBellEnabled: true,
  analyticsEnabled: true,
  analyticsExcludeAdminRoutes: true,
  analyticsRetentionLimit: 5000,
  analyticsShowDashboardCard: true,
};

export const sampleProducts: Product[] = [
  {
    id: '1', name: 'Rainbow Candy Grapes', slug: 'rainbow-candy-grapes', category: 'candy-grapes',
    description: 'Fresh grapes coated in a rainbow of candy shells. Each grape bursts with fruity flavor and a satisfying candy crackle.',
    shortDescription: 'Our signature rainbow candy-coated grapes.',
    price: 15, imageUrl: '/images/rainbow-grapes.png', flavorNotes: 'Mixed fruit flavors', colorThemeNotes: 'Rainbow',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '2', name: 'Blue Raspberry Grapes', slug: 'blue-raspberry-grapes', category: 'candy-grapes',
    description: 'Electric blue candy coating with a tart raspberry punch.',
    shortDescription: 'Sweet and tart blue raspberry.',
    price: 15, imageUrl: '/images/blue-grapes.png', flavorNotes: 'Blue Raspberry', colorThemeNotes: 'Blue',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '3', name: 'Pink Lemonade Grapes', slug: 'pink-lemonade-grapes', category: 'candy-grapes',
    description: 'Hot pink grapes with a refreshing lemonade zing.',
    shortDescription: 'Sweet and sour pink lemonade.',
    price: 15, imageUrl: '/images/pink-grapes.png', flavorNotes: 'Pink Lemonade', colorThemeNotes: 'Pink',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '4', name: 'Tropical Pineapple Chunks', slug: 'tropical-pineapple-chunks', category: 'candy-pineapple',
    description: 'Juicy pineapple chunks with a vibrant tropical candy shell.',
    shortDescription: 'Sweet candied pineapple.',
    price: 18, imageUrl: '/images/tropical-pineapple.png', flavorNotes: 'Tropical Punch', colorThemeNotes: 'Yellow/Orange',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '5', name: 'Mango Habanero Pineapple', slug: 'mango-habanero-pineapple', category: 'candy-pineapple',
    description: 'Spicy and sweet! Mango flavored candy coating with a kick of habanero.',
    shortDescription: 'Spicy sweet candied pineapple.',
    price: 20, imageUrl: '/images/mango-pineapple.png', flavorNotes: 'Mango, Habanero', colorThemeNotes: 'Orange/Red',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '6', name: 'Rainbow Party Tray (Small)', slug: 'rainbow-party-tray-small', category: 'party-trays',
    description: 'A beautiful arrangement of our best candy-coated fruits perfect for small gatherings.',
    shortDescription: 'Mixed tray for small parties.',
    price: 45, imageUrl: '/images/rainbow-tray.png', flavorNotes: 'Mixed', colorThemeNotes: 'Rainbow',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '7', name: 'Deluxe Celebration Tray', slug: 'deluxe-celebration-tray', category: 'party-trays',
    description: 'The ultimate candy fruit experience for large parties and events.',
    shortDescription: 'Large mixed tray for celebrations.',
    price: 85, imageUrl: '/images/deluxe-tray.png', flavorNotes: 'Mixed', colorThemeNotes: 'Rainbow/Custom',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: true, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '8', name: "Valentine's Special Grapes", slug: 'valentines-special-grapes', category: 'seasonal',
    description: 'Romantic red and pink candy-coated grapes, perfect for your sweetheart.',
    shortDescription: 'Seasonal romantic grapes.',
    price: 20, imageUrl: '/images/valentine-grapes.png', flavorNotes: 'Cherry, Strawberry', colorThemeNotes: 'Red/Pink',
    isAvailable: true, isFeatured: false, isSeasonal: true, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '9', name: 'Birthday Bash Custom Tray', slug: 'birthday-bash-custom-tray', category: 'custom',
    description: 'A totally custom tray tailored to your birthday theme and colors.',
    shortDescription: 'Custom tray for birthdays.',
    price: null, imageUrl: '/images/birthday-tray.png', flavorNotes: 'Custom', colorThemeNotes: 'Custom',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: true, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: 'donut-1', name: 'Glazed Crackzzz Donut', slug: 'glazed-crackzzz-donut', category: 'donutzzz',
    description: 'Classic ring donut with our signature candy-glaze drip and crunchy sugar shell.',
    shortDescription: 'Sweet glazed donut with candy crunch.',
    price: 4, imageUrl: '/images/donut-glazed.png', flavorNotes: 'Vanilla glaze', colorThemeNotes: 'Pink/Cream',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: 'donut-2', name: 'Birthday Cake Donutzzz Box', slug: 'birthday-cake-donutzzz-box', category: 'donutzzz',
    description: 'Half-dozen birthday cake donuts loaded with rainbow sprinkles and a candy-crack shell.',
    shortDescription: '6-pack of party-ready donuts.',
    price: 18, imageUrl: '/images/donut-box.png', flavorNotes: 'Birthday cake, sprinkles', colorThemeNotes: 'Rainbow',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: 'soda-1', name: 'Strawberry Cream Dirty Soda', slug: 'strawberry-cream-dirty-soda', category: 'dirty-sodazzz',
    description: 'Lemon-lime soda blended with strawberry puree, half-and-half, and a candy-rim cup.',
    shortDescription: 'Creamy strawberry-lime soda.',
    price: 7, imageUrl: '/images/soda-strawberry.png', flavorNotes: 'Strawberry, cream, lime', colorThemeNotes: 'Pink',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: 'soda-2', name: 'Coconut Mango Dirty Soda', slug: 'coconut-mango-dirty-soda', category: 'dirty-sodazzz',
    description: 'Cream soda with mango puree, coconut cream, and a sugar-crystal rim. Tropical and bold.',
    shortDescription: 'Tropical cream soda blend.',
    price: 7, imageUrl: '/images/soda-mango.png', flavorNotes: 'Mango, coconut cream', colorThemeNotes: 'Yellow/White',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
];

export const sampleMerchItems: MerchItem[] = [
  {
    id: 'merch-1',
    name: 'Candy Crackzzz Graffiti Tee',
    description: 'Bold candy-drip graffiti logo on a premium black tee. Soft, structured, and made to turn heads.',
    category: 'apparel',
    price: 30,
    salePrice: null,
    imageUrl: '/images/merch/graffiti-tee.png',
    status: 'available',
    inventory: 50,
    showInventory: false,
    isFeatured: true,
    isActive: true,
    allowPoints: true,
    allowFullPointsPurchase: false,
    pointsRequired: 300,
    maxPointsAllowed: 150,
    minPointsToRedeem: 50,
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    pickupShippingNote: 'Available for pickup or local delivery.',
    sortOrder: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'merch-2',
    name: 'Drip Flame Hoodie',
    description: 'Candy-drip flame sleeves with the CC logo on the chest. Heavyweight fleece, streetwear-ready.',
    category: 'apparel',
    price: 55,
    salePrice: null,
    imageUrl: '/images/merch/drip-flame-hoodie.png',
    status: 'available',
    inventory: 30,
    showInventory: false,
    isFeatured: true,
    isActive: true,
    allowPoints: true,
    allowFullPointsPurchase: false,
    pointsRequired: 550,
    maxPointsAllowed: 200,
    minPointsToRedeem: 100,
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    colors: ['Black'],
    pickupShippingNote: 'Available for pickup or local delivery.',
    sortOrder: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'merch-3',
    name: 'CC Drip Trucker Hat',
    description: 'Mesh back, structured front, CC candy-drip logo. One size fits all with an adjustable snapback.',
    category: 'accessories',
    price: 25,
    salePrice: null,
    imageUrl: '/images/merch/drip-trucker-hat.png',
    status: 'available',
    inventory: 40,
    showInventory: false,
    isFeatured: false,
    isActive: true,
    allowPoints: true,
    allowFullPointsPurchase: true,
    pointsRequired: 250,
    maxPointsAllowed: 125,
    minPointsToRedeem: 50,
    sizes: ['One Size'],
    colors: ['Black'],
    pickupShippingNote: 'Available for pickup.',
    sortOrder: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'merch-4',
    name: 'Galaxy Rhinestone Tumbler',
    description: 'Insulated 30oz stainless steel tumbler wrapped in a galaxy rhinestone drip design. Keeps drinks cold for hours.',
    category: 'drinkware',
    price: 45,
    salePrice: null,
    imageUrl: '/images/merch/rhinestone-tumbler.png',
    status: 'available',
    inventory: 20,
    showInventory: true,
    isFeatured: true,
    isActive: true,
    allowPoints: true,
    allowFullPointsPurchase: false,
    pointsRequired: 450,
    maxPointsAllowed: 200,
    minPointsToRedeem: 50,
    sizes: ['30oz'],
    colors: ['Galaxy Blue/Pink', 'Black'],
    pickupShippingNote: 'Fragile — pickup recommended. Handle with care if shipped.',
    sortOrder: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'merch-5',
    name: 'Candy Crackzzz Sticker Pack',
    description: '5-piece vinyl sticker pack featuring the CC logo, graffiti wordmark, and drip designs. Waterproof and bold.',
    category: 'stickers',
    price: 8,
    salePrice: null,
    imageUrl: '/images/merch/sticker-pack.png',
    status: 'available',
    inventory: 100,
    showInventory: false,
    isFeatured: false,
    isActive: true,
    allowPoints: true,
    allowFullPointsPurchase: true,
    pointsRequired: 80,
    maxPointsAllowed: 80,
    minPointsToRedeem: 30,
    sizes: [],
    colors: [],
    pickupShippingNote: 'Ships easily — available pickup or mail.',
    sortOrder: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'merch-6',
    name: 'CC Vendor Apron',
    description: 'Durable black apron with embroidered CC logo. Built for busy vendor days and candy events.',
    category: 'vendor',
    price: 35,
    salePrice: null,
    imageUrl: '/images/merch/vendor-apron.png',
    status: 'available',
    inventory: 15,
    showInventory: false,
    isFeatured: false,
    isActive: true,
    allowPoints: false,
    allowFullPointsPurchase: false,
    pointsRequired: 0,
    maxPointsAllowed: 0,
    minPointsToRedeem: 0,
    sizes: ['One Size'],
    colors: ['Black'],
    pickupShippingNote: 'Available for pickup.',
    sortOrder: 6,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'merch-7',
    name: 'CC Canvas Tote Bag',
    description: 'Heavy-duty canvas tote with the Candy Crackzzz graffiti logo. Use it for market days, pickups, and everything in between.',
    category: 'accessories',
    price: 20,
    salePrice: null,
    imageUrl: '/images/merch/canvas-tote.png',
    status: 'coming-soon',
    inventory: 0,
    showInventory: false,
    isFeatured: false,
    isActive: true,
    allowPoints: true,
    allowFullPointsPurchase: true,
    pointsRequired: 200,
    maxPointsAllowed: 100,
    minPointsToRedeem: 50,
    sizes: ['One Size'],
    colors: ['Black'],
    pickupShippingNote: 'Coming soon — check back!',
    sortOrder: 7,
    createdAt: new Date().toISOString(),
  },
];

export const sampleCampaigns: RewardsCampaign[] = [
  {
    id: 'camp-1',
    name: 'Birthday Crack Drop',
    type: 'birthday',
    rewardType: 'bonus-points',
    rewardValue: 25,
    isActive: true,
    expirationDays: 14,
    usageLimit: 0,
    onePerCustomer: true,
    minimumOrderAmount: 0,
    appliesTo: 'all',
    targetGroups: [],
    messageTemplate: "Happy Birthday! 🎂 Here's a sweet reward from Candy Crackzzz. Enjoy {reward} to celebrate your day!",
    birthdayWindowDaysBefore: 7,
    birthdayWindowDaysAfter: 7,
    sendMethods: ['in-app'],
    showOnHomepage: false,
    showAtCheckout: false,
    showInWallet: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'camp-2',
    name: 'First Order Reward',
    type: 'milestone',
    rewardType: 'bonus-points',
    rewardValue: 15,
    isActive: true,
    expirationDays: 30,
    usageLimit: 1,
    onePerCustomer: true,
    minimumOrderAmount: 0,
    appliesTo: 'all',
    targetGroups: [],
    messageTemplate: "Welcome to Candy Crackzzz! You earned {reward} bonus points on your first order. Sweet!",
    milestoneOrders: 1,
    sendMethods: ['in-app'],
    showOnHomepage: false,
    showAtCheckout: false,
    showInWallet: true,
    createdAt: new Date().toISOString(),
  },
];
