import type { Product, Settings } from '../types';

export const defaultSettings: Settings = {
  businessName: 'Candy Crackzzz',
  businessPhone: '',
  businessEmail: '',
  orderDestinationEmail: '',
  orderNotificationPhone: '',
  contactDestinationEmail: '',
  serviceArea: 'Spring Hill, FL and surrounding areas',
  aboutText: 'Candy Crackzzz is your ultimate destination for candy-coated fruit and custom treats.',
  socialLinks: { instagram: '', facebook: '', tiktok: '' },
  enableOrdering: true,
  enableCustomOrders: true,
  enableSeasonalSection: true,
  enableGallery: true,
  enableFeaturedSection: true,
  enablePickup: true,
  enableDelivery: true,
  deliveryFeeEnabled: false,
  deliveryFeeAmount: 10,
  minimumOrder: 20,
  showPricesPublicly: true,
  showSoldOutItems: true,
  allowRequestWithoutPrice: true,
  enableRewards: true,
  rewardsPointsPerDollar: 1,
  rewardsAwardOnCompletedOrder: true,
  rewardsAllowPromoStacking: false,
  rewardsTier1Points: 50,
  rewardsTier1Discount: 5,
  rewardsTier2Points: 100,
  rewardsTier2Discount: 12,
  rewardsTier3Points: 200,
  rewardsTier3Discount: 25,
  rewardsDoublePointsEnabled: false,
  rewardsFirstOrderBonusEnabled: false,
  rewardsFirstOrderBonusPoints: 10,
  rewardsBirthdayBonusEnabled: false,
  rewardsBirthdayBonusPoints: 15,
  rewardsSpendThresholdEnabled: false,
  rewardsSpendThresholdAmount: 50,
  rewardsSpendThresholdBonusPoints: 10,
  enableReferrals: true,
  referralReferrerBonusPoints: 15,
  referralReferredCustomerBonusPoints: 10,
  referralBonusOnFirstCompletedOrder: true,
  referralProgramDescription: 'Use a friend referral code at checkout so both of you can earn bonus points after the order is completed.',
  enablePromoTexts: false,
  promoTextsDescription: 'Customers who opt in can receive upcoming promotion texts later.',
  enablePayments: false,
  enableSquare: false,
  squarePaymentLink: '',
  squareInstructions: '',
  enableStripe: false,
  stripePaymentLink: '',
  stripeInstructions: '',
  enablePayPal: false,
  paypalContact: '',
  paypalInstructions: '',
  enableCashApp: false,
  cashAppTag: '',
  cashAppInstructions: '',
  enableVenmo: false,
  venmoUsername: '',
  venmoInstructions: '',
  enableZelle: false,
  zelleContact: '',
  zelleInstructions: '',
  enableQRCode: false,
  qrCodeImageBase64: '',
  qrCodeInstructions: '',
  enableManualInvoice: false,
  manualInvoiceInstructions: 'We will send you an invoice after confirming your order.',
  enableCashAtPickup: false,
  cashAtPickupInstructions: 'Pay cash when you pick up your order.',
  allowDepositOnly: false,
  allowFullPayment: true,
  allowCashAtPickup: false,
  allowManualInvoice: false,
  paymentInstructions: '',
  logoBase64: '',
  showLogo: true,
};

export const sampleProducts: Product[] = [
  {
    id: '1', name: 'Rainbow Candy Grapes', slug: 'rainbow-candy-grapes', category: 'candy-grapes',
    description: 'Fresh grapes coated in a rainbow of candy shells. Each grape bursts with fruity flavor and a satisfying candy crackle.',
    shortDescription: 'Our signature rainbow candy-coated grapes.',
    price: 15, imageUrl: '/images/rainbow-grapes.png', flavorNotes: 'Mixed fruit flavors', colorThemeNotes: 'Rainbow',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '2', name: 'Blue Raspberry Grapes', slug: 'blue-raspberry-grapes', category: 'candy-grapes',
    description: 'Electric blue candy coating with a tart raspberry punch.',
    shortDescription: 'Sweet and tart blue raspberry.',
    price: 15, imageUrl: '/images/blue-grapes.png', flavorNotes: 'Blue Raspberry', colorThemeNotes: 'Blue',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '3', name: 'Pink Lemonade Grapes', slug: 'pink-lemonade-grapes', category: 'candy-grapes',
    description: 'Hot pink grapes with a refreshing lemonade zing.',
    shortDescription: 'Sweet and sour pink lemonade.',
    price: 15, imageUrl: '/images/pink-grapes.png', flavorNotes: 'Pink Lemonade', colorThemeNotes: 'Pink',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '4', name: 'Tropical Pineapple Chunks', slug: 'tropical-pineapple-chunks', category: 'candy-pineapple',
    description: 'Juicy pineapple chunks with a vibrant tropical candy shell.',
    shortDescription: 'Sweet candied pineapple.',
    price: 18, imageUrl: '/images/tropical-pineapple.png', flavorNotes: 'Tropical Punch', colorThemeNotes: 'Yellow/Orange',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '5', name: 'Mango Habanero Pineapple', slug: 'mango-habanero-pineapple', category: 'candy-pineapple',
    description: 'Spicy and sweet! Mango flavored candy coating with a kick of habanero.',
    shortDescription: 'Spicy sweet candied pineapple.',
    price: 20, imageUrl: '/images/mango-pineapple.png', flavorNotes: 'Mango, Habanero', colorThemeNotes: 'Orange/Red',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '6', name: 'Rainbow Party Tray (Small)', slug: 'rainbow-party-tray-small', category: 'party-trays',
    description: 'A beautiful arrangement of our best candy-coated fruits perfect for small gatherings.',
    shortDescription: 'Mixed tray for small parties.',
    price: 45, imageUrl: '/images/rainbow-tray.png', flavorNotes: 'Mixed', colorThemeNotes: 'Rainbow',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '7', name: 'Deluxe Celebration Tray', slug: 'deluxe-celebration-tray', category: 'party-trays',
    description: 'The ultimate candy fruit experience for large parties and events.',
    shortDescription: 'Large mixed tray for celebrations.',
    price: 85, imageUrl: '/images/deluxe-tray.png', flavorNotes: 'Mixed', colorThemeNotes: 'Rainbow/Custom',
    isAvailable: true, isFeatured: true, isSeasonal: false, isCustomEligible: true, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '8', name: "Valentine's Special Grapes", slug: 'valentines-special-grapes', category: 'seasonal',
    description: 'Romantic red and pink candy-coated grapes, perfect for your sweetheart.',
    shortDescription: 'Seasonal romantic grapes.',
    price: 20, imageUrl: '/images/valentine-grapes.png', flavorNotes: 'Cherry, Strawberry', colorThemeNotes: 'Red/Pink',
    isAvailable: true, isFeatured: false, isSeasonal: true, isCustomEligible: false, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
  {
    id: '9', name: 'Birthday Bash Custom Tray', slug: 'birthday-bash-custom-tray', category: 'custom',
    description: 'A totally custom tray tailored to your birthday theme and colors.',
    shortDescription: 'Custom tray for birthdays.',
    price: null, imageUrl: '/images/birthday-tray.png', flavorNotes: 'Custom', colorThemeNotes: 'Custom',
    isAvailable: true, isFeatured: false, isSeasonal: false, isCustomEligible: true, isSoldOut: false, isVisible: true, createdAt: new Date().toISOString(),
  },
];
